apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app.kubernetes.io/component: deployments
    app.kubernetes.io/created-by: maintain-harbor
    app.kubernetes.io/managed-by: toolforge-jobs-framework
    app.kubernetes.io/name: test-cont-job-migration
    app.kubernetes.io/version: "1"
    jobs.toolforge.org/emails: none
    jobs.toolforge.org/filelog: "yes"
    toolforge: tool
  name: test-cont-job-migration
  namespace: tool-maintain-harbor
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: deployments
      app.kubernetes.io/created-by: maintain-harbor
      app.kubernetes.io/managed-by: toolforge-jobs-framework
      app.kubernetes.io/name: test-cont-job-migration
      app.kubernetes.io/version: "1"
      jobs.toolforge.org/emails: none
      jobs.toolforge.org/filelog: "yes"
      toolforge: tool
  template:
    metadata:
      labels:
        app.kubernetes.io/component: deployments
        app.kubernetes.io/created-by: maintain-harbor
        app.kubernetes.io/managed-by: toolforge-jobs-framework
        app.kubernetes.io/name: test-cont-job-migration
        app.kubernetes.io/version: "1"
        jobs.toolforge.org/emails: none
        jobs.toolforge.org/filelog: "yes"
        toolforge: tool
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - --
            - ./test_cont_script.sh 1>>test-cont-job-migration.out
              2>>test-cont-job-migration.err
          env:
            - name: HOME
              value: /data/project/maintain-harbor
          image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
          imagePullPolicy: Always
          name: test-cont-job-migration
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: "536870912"
          volumeMounts:
            - mountPath: /data/project
              name: home
          workingDir: /data/project/maintain-harbor
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /data/project
            type: Directory
          name: home
