chartVersion: 0.0.19-20241001092739-d389755b
chartRepository: toolsbeta
replicas: 1
config:
  debug: true
certificates:
  internalClusterDomain: cluster.local
image:
  pullPolicy: Always
resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
