chartVersion: 0.0.171-20251023075757-a5105f4d
# Use tools for now, as we are developing too quick without deploying
# and the toolsbeta images are getting deleted
chartRepository: tools
replicas: 1
config:
  debug: true
  toolforge_api_url: "https://api-gateway.api-gateway.svc"
  verify_toolforge_api_cert: false
certificates:
  internalClusterDomain: cluster.local
image:
  pullPolicy: Always
resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
