chartVersion: 0.0.17-20240902084955-4746c939
chartRepository: toolsbeta
replicas: 1
config:
  debug: true
certificates:
  internalClusterDomain: cluster.local
resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
