---
# NOTE: never delete this file, keep for deploy script
kubeVersion: ">= 1.24 <= 1.26"

admissionController:
  replicas: 1
  container:
    resources: ~
  initContainer:
    resources: ~

backgroundController:
  replicas: 1
  resources: ~

cleanupController:
  replicas: 1
  resources: ~

reportsController:
  replicas: 1
  resources: ~
