# Update to your mr version tag
chartVersion: 0.0.18-20251029114245-20cc47fb
chartRepository: toolsbeta
# When changing the chart version, make sure to update kubeVersion
# See
#  https://docs.tigera.io/calico/3.28/getting-started/kubernetes/requirements
#   and https://gitlab.wikimedia.org/repos/cloud/toolforge/calico/-/blob/main/deployment/chart/values.yaml#L6
kubeVersion: ">=1.27 <=1.30"

typha_replicas: 1
