# Update to your mr version tag
chartVersion: 0.0.15-20241104101859-e2c4ee9b
chartRepository: toolsbeta
# When changing the chart version, make sure to update kubeVersion
# See
#  https://docs.tigera.io/calico/3.26/getting-started/kubernetes/requirements
#   and https://gitlab.wikimedia.org/repos/cloud/toolforge/calico/-/blob/main/deployment/chart/values.yaml#L6
kubeVersion: ">=1.24 <=1.28"

typha_replicas: 1
