# Update to your mr version tag
chartVersion: 0.0.9-20240827072036-84ea5a22
chartRepository: toolsbeta
# When changing the chart version, make sure to update kubeVersion
# See
#   https://docs.tigera.io/archive/v3.24/getting-started/kubernetes/requirements
#   and https://gitlab.wikimedia.org/repos/cloud/toolforge/calico/-/blob/main/deployment/chart/values.yaml#L6
kubeVersion: ">=1.22 <=1.25"
