chartVersion: 4.11.2
controller:
  replicaCount: 1
  extraArgs:
    default-backend-service: null
  config:
    custom-http-errors: ""
  # lima-kilo vm is not that big
  resources:
    requests:
      cpu: 1
      memory: 1G
# When changing the chart version, make sure to update kubeVersion
# See:
#    https://github.com/kubernetes/ingress-nginx/tree/main#supported-versions-table
kubeVersion: ">=1.26 <=1.30"
