chartVersion: 4.3.0
controller:
  replicaCount: 1
# When changing the chart version, make sure to update kubeVersion
# See:
#    https://github.com/kubernetes/ingress-nginx/tree/main#supported-versions-table
kubeVersion: ">=1.22 <=1.25"
