---
repositories:
  - name: toolsbeta
    url: toolsbeta-harbor.wmcloud.org/toolforge
    oci: true
  - name: tools
    url: tools-harbor.wmcloud.org/toolforge
    oci: true

releases:
  - name: jobs-emailer
    chart: "{{ .Values.chartRepository }}/jobs-emailer"
    version: "{{ .Values.chartVersion }}"
    namespace: jobs-emailer
    createNamespace: true
    values:
      - values/{{ .Environment.Name }}.yaml*

environments:
  local:
    values:
      # needed to use the chartVersion
      - values/{{ .Environment.Name }}.yaml*
  toolsbeta:
    values:
      # needed to use the chartVersion
      - values/{{ .Environment.Name }}.yaml*
  tools:
    values:
      # needed to use the chartVersion
      - values/{{ .Environment.Name }}.yaml*
