# Update to your mr version tag
chartVersion: 0.0.86-20260610023314-4ef665f5
chartRepository: toolsbeta
replicas: 1
config:
  debug: true
certificates:
  internalClusterDomain: cluster.local

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
