# Update to your mr version tag
chartVersion: 0.0.85-20260601140148-25e4f0fb
chartRepository: toolsbeta
replicas: 1
config:
  debug: true
certificates:
  internalClusterDomain: cluster.local

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
