# Update to your mr version tag
chartVersion: 0.0.77-20251103105359-23dc2571
chartRepository: toolsbeta
replicas: 1
config:
  debug: true
certificates:
  internalClusterDomain: cluster.local

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
