# Update to your mr version tag
chartVersion: 0.0.82-20260304125430-4d1e4c78
chartRepository: toolsbeta
replicas: 1
config:
  debug: true
certificates:
  internalClusterDomain: cluster.local

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
