# Update to your mr version tag
chartVersion: 0.0.44-20240705083909-fbafef28
chartRepository: toolsbeta
replicaCount: 1
allowedRegistries:
  - "docker-registry.tools.wmflabs.org"
  - "toolsbeta-harbor.wmcloud.org"
  - "tools-harbor.wmcloud.org"
