# Update to your mr version tag
chartVersion: 0.0.43-20240701123945-624fca18
chartRepository: toolsbeta
replicaCount: 1
allowedRegistries:
  - "docker-registry.tools.wmflabs.org"
  - "toolsbeta-harbor.wmcloud.org"
  - "tools-harbor.wmcloud.org"
