# Update to your mr version tag
chartVersion: 0.0.46-20240710155426-ae29a6f9
chartRepository: toolsbeta
replicaCount: 1
allowedRegistries:
  - "docker-registry.tools.wmflabs.org"
  - "toolsbeta-harbor.wmcloud.org"
  - "tools-harbor.wmcloud.org"
