# Update to your mr version tag
chartVersion: 0.0.42-20240612171641-a8eaf992
chartRepository: toolsbeta
replicaCount: 1
allowedRegistries:
  - "docker-registry.tools.wmflabs.org"
  - "toolsbeta-harbor.wmcloud.org"
  - "tools-harbor.wmcloud.org"
