# Update to your mr version tag
chartVersion: 0.0.40-20240603080405-5c500731
chartRepository: toolsbeta
replicaCount: 1
allowedRegistries:
  - "docker-registry.tools.wmflabs.org"
  - "toolsbeta-harbor.wmcloud.org"
  - "tools-harbor.wmcloud.org"
