repositories:
  - name: toolsbeta
    url: toolsbeta-harbor.wmcloud.org/toolforge
    oci: true
  - name: tools
    url: tools-harbor.wmcloud.org/toolforge
    oci: true

releases:
  - name: maintain-harbor
    chart: "{{ .Values.chartRepository }}/maintain-harbor"
    version: "{{ .Values.chartVersion }}"
    namespace: maintain-harbor
    createNamespace: true
    values:
      - values/{{ .Environment.Name }}.yaml*

environments:
  local:
    values:
      # needed to use the chartVersion
      - values/{{ .Environment.Name }}.yaml*
  toolsbeta:
    values:
      # needed to use the chartVersion
      - values/{{ .Environment.Name }}.yaml*
  tools:
    values:
      # needed to use the chartVersion
      - values/{{ .Environment.Name }}.yaml*
