# Update to your mr version tag
chartVersion: 0.0.22-20241120104704-1c22695e
chartRepository: toolsbeta
replicas: 1
config:
  debug: true

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
