# Update to your mr version tag
chartVersion: 0.0.35-20251110182447-94859fd1
chartRepository: toolsbeta
replicas: 1
config:
  debug: true
  extraEnvvars:
    - name: TOOL_TOOLFORGE_API_URL
      value: "https://api-gateway.api-gateway.svc"
    - name: TOOL_REDIS_URI
      value: "notsetup"
    - name: TOOL_ELASTICSEARCH_URL
      value: "notsetup"
