# Update to your mr version tag
chartVersion: 0.0.31-20250805004511-3ae60417
chartRepository: toolsbeta
replicas: 1
config:
  debug: true
  extraEnvvars:
    - name: TOOL_TOOLFORGE_API_URL
      value: "https://api-gateway.api-gateway.svc"
    - name: TOOL_REDIS_URI
      value: "notsetup"
    - name: TOOL_ELASTICSEARCH_URL
      value: "notsetup"
