environments:
  local:
    values:
      # needed to use the chartVersion
      - values/common.yaml
      - values/{{ .Environment.Name }}.yaml
  toolsbeta:
    values:
      # needed to use the chartVersion
      - values/common.yaml
      - values/{{ .Environment.Name }}.yaml
---
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  # Instance for storing tool logs.
  - name: loki-tools
    namespace: loki
    createNamespace: true
    chart: grafana/loki
    version: "{{ .Values.loki.chartVersion }}"
    values:
      - values/loki/common.yaml
      - values/loki/{{ .Environment.Name }}.yaml*
      - values/loki-tools/common.yaml
      - values/loki-tools/{{ .Environment.Name }}.yaml
  # Instance for storing infrastructure logs.
  - name: loki-infrastructure
    namespace: loki
    chart: grafana/loki
    version: "{{ .Values.loki.chartVersion }}"
    values:
      - values/loki/common.yaml
      - values/loki/{{ .Environment.Name }}.yaml*
      - values/loki-infrastructure/common.yaml
      - values/loki-infrastructure/{{ .Environment.Name }}.yaml
  - name: alloy
    # This needs a separate namespace for network policy reasons.
    namespace: alloy
    createNamespace: true
    chart: grafana/alloy
    version: "{{ .Values.alloy.chartVersion }}"
    values:
      - values/alloy/common.yaml*
