replicas: 1
resources:
  limits:
    cpu: 1
    memory: 1G
  requests:
    cpu: 50m
    memory: 128Mi

enableAffinity: false

# volumes and volumeMounts required for macOS lima-kilo;
# otherwise istio-gateway fails with "Failed to create temporary file" (T425479).
volumes:
  - name: tmp
    emptyDir: {}

volumeMounts:
  - name: tmp
    mountPath: /tmp
