# this is for local development
chartVersion: 0.0.76-20260122175000-402ddb48
chartRepository: toolsbeta

replicas: 1
debug: true
domains:
  - local

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
