# this is for local development
chartVersion: 0.0.70-20251110182813-e6936b2b
chartRepository: toolsbeta

replicas: 1
debug: true
domains:
  - local

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
