# this is for local development
chartVersion: 0.0.85-20260303181419-22df37af
chartRepository: toolsbeta

replicas: 1
debug: true
domains:
  - local

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
