# this is for local development
chartVersion: 0.0.54-20241119090358-300b9ae5
chartRepository: toolsbeta

replicas: 1
debug: true
domains:
  - local

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
