# this is for local development
chartVersion: 0.0.77-20260128152724-d2dfd2a6
chartRepository: toolsbeta

replicas: 1
debug: true
domains:
  - local

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
