# this is for local development
chartVersion: 0.0.49-20240902122319-b0b4ce16
chartRepository: toolsbeta

replicas: 1
debug: true
domains:
  - local

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
