chartVersion: 0.0.26-20240702121120-cebdcedc
chartRepository: toolsbeta

certificates:
  internalClusterDomain: cluster.local
  extraNames:
    # this is useful in the lima-kilo kind context, harmless if not
    - toolforge-control-plane

app:
  log_level: debug
