chartVersion: 0.0.30-20240725144339-331dbe65
chartRepository: toolsbeta

certificates:
  internalClusterDomain: cluster.local
  extraNames:
    # this is useful in the lima-kilo kind context, harmless if not
    - toolforge-control-plane

app:
  log_level: debug
