chartVersion: 0.0.41-20240826085537-205b142a
chartRepository: toolsbeta

certificates:
  internalClusterDomain: cluster.local
  extraNames:
    # this is useful in the lima-kilo kind context, harmless if not
    - toolforge-control-plane

app:
  log_level: debug
  api_maps:
    builds: "https://builds-api.builds-api.svc.cluster.local:8443"
    jobs: "https://jobs-api.jobs-api.svc.cluster.local:8443"
    envvars: "https://envvars-api.envvars-api.svc.cluster.local:8443"
