chartVersion: 0.0.17-20230831092149-cf3e484f
chartRepository: tools

certificates:
  internalClusterDomain: cluster.local
  extraNames:
    # this is useful in the lima-kilo kind context, harmless if not
    - toolforge-control-plane
