chartVersion: 0.0.19-20240411190537-c937fb4a
chartRepository: tools

certificates:
  internalClusterDomain: cluster.local
  extraNames:
    # this is useful in the lima-kilo kind context, harmless if not
    - toolforge-control-plane
