chartVersion: 0.1.1-dev.mr8
chartRepository: toolsbeta
# Please edit this file according to what you have deployed on your local cluster.
# Leaving empty so basic deploy does not fail right away
backends: []
# Examples of entries:
#   - name: jobs-api
#     path: /jobs
#     target:
#       namespace: jobs-api
#       service: jobs-api
#       port: 8443
#   - name: builds-api
#     path: /builds
#     target:
#       namespace: builds-api
#       service: builds-api
#       port: 8443

certificates:
  extraNames:
    # this is useful in the lima-kilo kind context, harmless if not
    - toolforge-control-plane
