chartVersion: 0.0.44-20240902122941-a7ca33e8
chartRepository: toolsbeta

certificates:
  internalClusterDomain: cluster.local
  extraNames:
    # this is useful in the lima-kilo kind context, harmless if not
    - toolforge-control-plane

app:
  log_level: debug
  api_maps:
    builds: "https://builds-api.builds-api.svc.cluster.local:8443"
    jobs: "https://jobs-api.jobs-api.svc.cluster.local:8443"
    envvars: "https://envvars-api.envvars-api.svc.cluster.local:8443"

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
