chartVersion: 0.0.81-20251016082112-1c4f5a64
chartRepository: toolsbeta
certificates:
  internalClusterDomain: cluster.local
  extraNames:
    # this is useful in the lima-kilo kind context, harmless if not
    - toolforge-control-plane

app:
  log_level: debug
  superusers:
    - service:components-api
  api_maps:
    builds: "https://builds-api.builds-api.svc.cluster.local:8443"
    jobs: "https://jobs-api.jobs-api.svc.cluster.local:8443"
    envvars: "https://envvars-api.envvars-api.svc.cluster.local:8443"
    components: "https://components-api.components-api.svc.cluster.local:8443"
  openapi_docs:
    components: true
    external_servers:
      - url: "https://127.0.0.1:30003"
        description: "External server."
      - url: "https://127.0.0.1:30003"
        description: "Internal server, only reachable from within toolforge."

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
