chartVersion: 0.0.18-20240110162223-d979a5b7
chartRepository: tools

certificates:
  internalClusterDomain: cluster.local
  extraNames:
    # this is useful in the lima-kilo kind context, harmless if not
    - toolforge-control-plane
