chartVersion: 0.0.23-20240603075945-18fc26ce
chartRepository: toolsbeta

certificates:
  internalClusterDomain: cluster.local
  extraNames:
    # this is useful in the lima-kilo kind context, harmless if not
    - toolforge-control-plane

app:
  log_level: debug
