chartVersion: 0.0.22-20240514132013-9d1a4346
chartRepository: toolsbeta

certificates:
  internalClusterDomain: cluster.local
  extraNames:
    # this is useful in the lima-kilo kind context, harmless if not
    - toolforge-control-plane

app:
  log_level: debug
