chartVersion: 0.0.20-20240628101504-9ed20c1f
chartRepository: toolsbeta
# Also update kubeVersion when updating the kube-state-metrics chart
# for compatibility info see:
#  https://github.com/kubernetes/kube-state-metrics?tab=readme-ov-file#compatibility-matrix
#  and
#  https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/Chart.yaml
#
# Current is <= 1.27, see
#   https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/Chart.yaml
# this v5.16.4 chart should pull v2.10.1, which is usually cached in our registry
# see also:
#  https://explore.ggcr.dev/?image=registry.k8s.io%2Fkube-state-metrics%2Fkube-state-metrics:v2.10.1
#  components/wmcs-k8s-metrics/values/common/kube-state-metrics.yaml
kubeStateMetricsChartVersion: v5.16.4
# see with `helm search repo --versions wmf-stable/raw``, with wmf-stable repo installed (ex. lima-kilo)
metricsServerApiCertsChartVersion: v0.3.0
# chart version from https://artifacthub.io/packages/helm/metrics-server/metrics-server
metricsServerChartVersion: v3.12.1
# When changing the chart version, make sure to update kubeVersion
# See
#   https://artifacthub.io/packages/helm/metrics-server/metrics-server -> for the appVersion
#   https://github.com/kubernetes-sigs/metrics-server#compatibility-matrix
#
# Current is >=1.19
#
# The following is a combination of kube-state-metrics version requirement and metrics-server
kubeVersion: ">=1.19 <=1.27"
