chartVersion: 0.0.45-20260826093712-2d6a3f95
chartRepository: tools
replicas: 1
config:
  debug: true
  runtime_loki_read_url: "http://loki-tools.loki.svc:3100/loki"
  runtime_loki_write_url: "http://loki-tools.loki.svc:3100/loki"
certificates:
  internalClusterDomain: cluster.local
image:
  pullPolicy: Always
resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
