chartVersion: 0.0.8-20251125011956-f50aaf4b
chartRepository: tools
replicas: 1
config:
  debug: true
  runtime_loki_url: "http://loki-tools.loki.svc:3100/loki"
certificates:
  internalClusterDomain: cluster.local
image:
  pullPolicy: Always
resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
