#!/usr/bin/env bats
# shellcheck disable=SC2155
# SC2155 (warning): Declare and assign separately to avoid masking return values.
# bats file_tags=tools,components-api,smoke
set -o nounset

setup_file() {
    load "components-common"
    export BATS_NO_PARALLELIZE_WITHIN_FILE=true
    export MIN_BATS_VERSION=1.5.0
    flush_everything
}

setup() {
    load "components-common"
    _components_setup
    export TOOL_NAME="${USER#*.}"

    cat > "$BATS_FILE_TMPDIR"/main-ref-sourcebuild-test-config.yaml <<EOC
config_version: "v1beta1"
components:
  component1:
    component_type: continuous
    build:
      repository: $SAMPLE_REPO_URL
      ref: main
    run:
      command: web
EOC
    cat > "$BATS_FILE_TMPDIR"/dummy-ref-sourcebuild-test-config.yaml <<EOC
config_version: "v1beta1"
components:
  component1:
    component_type: continuous
    build:
      repository: $SAMPLE_REPO_URL
      ref: dummy_branch
    run:
      command: web
EOC
}

@test "config create works" {
    run --separate-stderr toolforge components config create "$BATS_FILE_TMPDIR"/main-ref-sourcebuild-test-config.yaml
    assert_success
}

@test "config show works" {
    run --separate-stderr toolforge components config show
    assert_success
    assert_line --partial "component1:"
}

@test "config update works" {
    run --separate-stderr toolforge components config show
    assert_success
    assert_line --partial "ref: main"
    refute_line --partial "ref: dummy_branch"

    # update config
    run --separate-stderr toolforge components config create "$BATS_FILE_TMPDIR"/dummy-ref-sourcebuild-test-config.yaml
    assert_success

    # ensure config now has the string "dummy_branch" not "main"
    run --separate-stderr toolforge components config show
    assert_success
    refute_line --partial "ref: main"
    assert_line --partial "ref: dummy_branch"
}

@test "config generate with no existing jobs works and is loadable" {
    flush_jobs

    run toolforge components config generate > "$BATS_FILE_TMPDIR"/generated-config.yaml
    assert_success
    assert_line --partial "No components were able to be generated from your tool, a sample set of them is returned instead"
    assert_line --partial "Note that this config is an autogenerated example, please double check and validate before using it"

    # update config with the generated one
    run --separate-stderr toolforge components config create "$BATS_FILE_TMPDIR"/generated-config.yaml
    assert_success
}

@test "deploy token create works" {
    toolforge components deploy-token delete --yes-im-sure &>/dev/null || :
    run --separate-stderr toolforge components deploy-token create
    assert_success
    assert_line --partial "Token:"
}

@test "deploy token show works" {
    toolforge components deploy-token delete --yes-im-sure &>/dev/null || :
    toolforge components deploy-token create

    run --separate-stderr toolforge components deploy-token show
    assert_success
    assert_line --partial "Token:"
}

@test "deploy token refresh works" {
    local old_token=$(toolforge components deploy-token show --json | jq -r '.token')

    run --separate-stderr toolforge components deploy-token refresh --yes-im-sure
    assert_success
    local new_token=$(echo "$output" | grep "Token:" | cut -d' ' -f2)
    assert_not_equal "$old_token" "$new_token"
}

@test "creating a deployment with invalid token fails" {
    local invalid_token="3fae991e-193c-4b86-9f6a-im1nv4l1d"

    run --separate-stderr bash -c "curl --insecure -X POST '$TOOLFORGE_API_URL/components/v1/tool/$TOOL_NAME/deployment?token=$invalid_token' | jq"
    assert_success
    assert_line --partial "does not match the tool's token"
}

@test "can create deployment using the cli" {
    toolforge components config create "$BATS_FILE_TMPDIR"/main-ref-sourcebuild-test-config.yaml

    run --separate-stderr toolforge components deployment create
    assert_success
    assert_line --partial "created successfully"

    local deployment_id=$(toolforge components deployment list --json | jq -r '.data.deployments[-1].deploy_id')

    retry "toolforge components deployment show $deployment_id --json | jq -e '.status == \"running\"'" 20
}

@test "can create deployment using the token" {
    local token=$(toolforge components deploy-token show --json | jq -r '.token')
    # we can only have one deployment at a time, so flush any existing deployments
    flush_deployments
    flush_builds

    run --separate-stderr bash -c "curl --silent -v --insecure -X POST '$TOOLFORGE_API_URL/components/v1/tool/$TOOL_NAME/deployment?token=$token' | jq -r .messages.info[0]"
    assert_success
    assert_line "Deployment for $TOOL_NAME created successfully."
}

@test "deployment list works" {
    run --separate-stderr toolforge components deployment list
    assert_success
    assert_line --partial "ID"
    assert_line --partial "component1"
}

@test "deployment show works" {
    local deploy_id=$(toolforge components deployment list --json | jq -r '.data.deployments[-1].deploy_id')
    run --separate-stderr toolforge components deployment show "$deploy_id"
    assert_success
    assert_line --partial "$deploy_id"
}

@test "deploy token delete works" {
    toolforge components deploy-token delete --yes-im-sure &>/dev/null || :
    toolforge components deploy-token create

    run --separate-stderr toolforge components deploy-token delete --yes-im-sure
    assert_success

    run toolforge components deploy-token show
    assert_line --partial "Unable to find"
}

# bats test_tags=slow
@test "config generate with some existing jobs works, is loadable and creates the same job (slow)" {
    bats_require_minimum_version "$MIN_BATS_VERSION"
    # reuses the deployment created earlier
    local deployment_id=$(toolforge components deployment list --json | jq -r '.data.deployments[-1].deploy_id')
    wait_for_successful_deployment "${deployment_id}"
    toolforge jobs dump > "$BATS_FILE_TMPDIR"/before_generate.yaml

    # Generate config works
    run toolforge components config generate > "$BATS_FILE_TMPDIR"/existing-jobs-generated-config.yaml
    assert_success
    refute_line --partial "No components were able to be generated from your tool, a sample set of them is returned instead"
    assert_line --partial "Note that this config is an autogenerated example, please double check and validate before using it"

    # Loading the generated config works
    run --separate-stderr toolforge components config create "$BATS_FILE_TMPDIR"/existing-jobs-generated-config.yaml
    assert_success

    # this one should be fast as it reuses the build and the job
    local deployment_id=$(create_deployment)
    wait_for_successful_deployment "${deployment_id}"
    run --separate-stderr toolforge jobs dump

    # The job the deploy generates is the same that was there
    assert_output "$(cat "$BATS_FILE_TMPDIR"/before_generate.yaml)"
}

@test "deployment delete works" {
    local deploy_id=$(toolforge components deployment list --json | jq -r '.data.deployments[-1].deploy_id')
    run --separate-stderr toolforge components deployment delete --yes-im-sure "$deploy_id"
    assert_success
    assert_line --partial "deleted successfully"
}

@test "config delete works" {
    run --separate-stderr toolforge components config delete --yes-im-sure
    assert_success

    run toolforge components config show
    refute_line --partial "components:"
}

teardown() {
    _components_teardown
}
