chartVersion: 0.0.203-20261005123458-89615cdc
chartRepository: toolsbeta
replicas: 1

image:
  args:
    [
      "/app/maintain_kubeusers_cli.py",
      "--project=toolsbeta",
      "--debug",
      "--interval=60",
    ]

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
