chartVersion: 0.0.187-20251104133257-2e7abefc
chartRepository: toolsbeta
replicas: 1

image:
  args:
    [
      "/app/maintain_kubeusers_cli.py",
      "--project=toolsbeta",
      "--debug",
      "--interval=60",
    ]

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
