chartVersion: 0.0.202-20260902134959-47547230
chartRepository: toolsbeta
replicas: 1

image:
  args:
    [
      "/app/maintain_kubeusers_cli.py",
      "--project=toolsbeta",
      "--debug",
      "--interval=60",
    ]

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
