chartVersion: 0.0.183-20250924080007-93ad9a3f
chartRepository: toolsbeta
replicas: 1

image:
  args:
    [
      "/app/maintain_kubeusers_cli.py",
      "--project=toolsbeta",
      "--debug",
      "--interval=60",
    ]

resources:
  limits:
    memory: ~
    cpu: ~
  requests:
    memory: ~
    cpu: ~
