environments:
  local:
    values:
      # needed to use the chartVersion
      - values/common.yaml*
      - values/{{ .Environment.Name }}.yaml*
  tools:
    values:
      # needed to use the chartVersion
      - values/common.yaml*
      - values/{{ .Environment.Name }}.yaml*
  toolsbeta:
    values:
      # needed to use the chartVersion
      - values/common.yaml*
      - values/{{ .Environment.Name }}.yaml*
---
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  # Instance for storing tools interdependency tracing logs
  - name: loki-tracing
    namespace: loki-tracing
    createNamespace: true
    chart: grafana/loki
    version: "{{ .Values.loki.chartVersion }}"
    values:
      - ../common/values/loki/common.yaml*
      - ../common/values/loki/{{ .Environment.Name }}.yaml*
      - values/{{ .Environment.Name }}.yaml*
      - values/common.yaml*
